version: "3"
networks:
  minternet:
services:
  minter:
    image: minter/minter:latest
    command: --tendermint_addr=tcp://tendermint:46657
    volumes:
          - ~/.minter:/minter
    ports:
      - "8841:8841"
      - "46658:46658"
    networks:
      minternet:
  tendermint:
    image: tendermint/tendermint:0.19.7
    command: node --proxy_app=tcp://minter:46658
    volumes:
      - ~/.tendermint:/tendermint
    ports:
      - "46656:46656"
      - "46657:46657"
    networks:
      minternet: